import "@/styles/globals.css";
import ProtectedRoutes from "@/components/ProtectedRoutes";

export const metadata = {
  title: 'SASB',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <ProtectedRoutes>
          {children}
        </ProtectedRoutes>
      </body>
    </html>
  )
}
